#!/usr/bin/env sh

echo "🔍 Checking commit message..."

pnpm exec commitlint --edit "$1"

if [ $? -ne 0 ]; then
  echo "❌ Invalid commit message."
  echo "Use format: type: description"
  echo "Example: feat: add product page"
fi
